### ISSUE TITLE
What IAM policies are required to deploy this?

### ISSUE THREAD

**Issue by samjarrett** [tombolaltd/ecs-monitor#26]
Hi, the screenshots for this look like it would be very useful - wanting to deploy it ourselves and was wondering: what IAM policies do we need to grant this app to work?

**Comment by marc-costello** [comment]
Hi @samjarrett, excellent question, the readme needs updating with this information and I'll attach a sample policy document asap, but in the mean time the monitor needs:

- EC2 Describe instances
- ECS List and describe clusters
- ECS List & describe container instances
- ECS List & describe services
- ECS List task definitions
- ECS List & describe tasks
- CloudWatch describe log streams
- CloudWatch get log events
- CloudWatch get metric stats

So essentially its list & describe permissions for EC2, ECS and CloudWatch - But as I say I'll attach a sample/recommended policy document asap.

**Comment by marc-costello** [comment]
I've attached a recommended IAM policy which can be found [here](/aws/policy.json)
